### PR TITLE
Update SharedUtilsFunctions.ps1 for ExaGrid

### PR DESCRIPTION
**Pull request by MicKBfr**
Add ExaGrid support

## Description
Add support of ExaGrid Appliance 

## Related Issue
Exagrid Appliance not display in graph repository

## Motivation and Context
Some veeam user have Exagrid Appliance 

## How Has This Been Tested?
Test with Exagrid appliance succesfull

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by MicKBfr** [comment]
Hi,
First of all,  thanks for all your work for this project.
A little pull request to support exagrid dedup appliance
We use it and i need to add repository on ExaGrid

Thanks
Best regards

**Comment by rebelinux** [comment]
Thanks for your contribution!

**Comment by rebelinux** [comment]
> Hi, First of all, thanks for all your work for this project. A little pull request to support exagrid dedup appliance We use it and i need to add repository on ExaGrid
> 
> Thanks Best regards

Question for you:

Do you use the AsBuiltReport.Veeam.VBR or do you just use Veeam.Diagrammer to create your documentation?

**Comment by MicKBfr** [comment]
Hello, i discovered this project with AsBuiltReport.Veeam.VBR.
At this time, i have just some test with Veeam.Diagrammer but i will try report on next days
Thanks for commit

**Pull request merged**
